<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>ExampleProvider.UnmaApiSample</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="UnmaIntegration.cs" />
    <ProjectReference Include="..\..\source\UNMA.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
